//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "token_on_ledger")]
pub struct Model {
	pub chain_id: String,
	#[sea_orm(primary_key, auto_increment = false)]
	pub token_id: String,
	pub decimals: i16,
	pub e_chain_amount: String,
	pub s_chain_amount: String,
	pub hub_amount: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
