//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "token_on_chain")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub chain_id: String,
	#[sea_orm(primary_key, auto_increment = false)]
	pub token_id: String,
	pub amount: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
